sh-5.1$ python3 -m unittest runTest.py 
E
======================================================================
ERROR: test_correct_withdraw_amount (runTest.TestRedOrBlueFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/code/digital_nomad_CFG/temp-repo/runTest.py", line 43, in test_correct_withdraw_amount
    with patch('__builtin__.raw_input', withdrawal=int(99)) as _raw_input:
  File "/home/user/.var/app/com.vscodium.codium/data/python/lib/python3.9/site-packages/mock/mock.py", line 1398, in __enter__
    self.target = self.getter()
  File "/home/user/.var/app/com.vscodium.codium/data/python/lib/python3.9/site-packages/mock/mock.py", line 1573, in <lambda>
    getter = lambda: _importer(target)
  File "/home/user/.var/app/com.vscodium.codium/data/python/lib/python3.9/site-packages/mock/mock.py", line 1245, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named '__builtin__'

----------------------------------------------------------------------
Ran 1 test in 0.001s

